import React from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import {
  Image,
  Scissors,
  Palette,
  RefreshCw,
  Eraser,
  Brush,
  Crop,
  Maximize as Resize,
  Sparkles,
  Filter,
  Eye,
  Download,
  Grid,
  Type,
  Zap,
  Camera,
  Layers,
  Move,
  RotateCw,
  Contrast,
  Sun,
  Moon,
  Droplets,
  Wand2,
  Scan,
  FileImage,
  Sliders,
  Target,
  Aperture,
  Focus,
  Lightbulb,
  Gauge,
  Blend,
  Shapes,
  PaintBucket,
  Stamp,
  Magnet,
  Crosshair,
  Maximize2,
  Minimize2,
  FlipHorizontal,
  FlipVertical,
  CornerDownRight,
  Square,
  Circle,
  Triangle,
  Star,
  Smile,
  Frown,
  Meh,
  Users,
  Baby,
  User,
  UserCheck,
  Fingerprint,
  Shield,
  Lock,
  Unlock,
  Key,
  Database,
  Code,
  Hash,
  Binary,
  Cpu,
  HardDrive,
  Wifi,
  Bluetooth,
  Smartphone,
  Monitor,
  Printer,
  Scanner,
  Webcam,
  Mic,
  Volume2,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Music,
  Headphones,
  Radio,
  Tv,
  Film,
  Video,
  ImageIcon,
  FileText,
  Folder,
  Archive,
  Package,
  Gift,
  ShoppingBag,
  CreditCard,
  DollarSign,
  TrendingUp,
  BarChart,
  PieChart,
  Activity,
  Zap as Lightning,
  Flame,
  Snowflake,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  MapPin,
  Navigation,
  Compass,
  Map,
  Globe,
  Plane,
  Car,
  Truck,
  Bus,
  Train,
  Ship,
  Anchor,
  Home,
  Building,
  Factory,
  Store,
  School,
  Hospital,
  Church,
  TreePine,
  Flower,
  Leaf,
  Feather,
  Bug,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  Butterfly,
  Bee,
  Spider,
  Snail,
  Worm,
  Ant,
  Ladybug,
  Dragonfly,
  Mosquito,
  Fly,
  Beetle,
  Cockroach,
  Scorpion,
  Snake,
  Lizard,
  Frog,
  Mouse,
  Rat,
  Hamster,
  Squirrel,
  Hedgehog,
  Bat,
  Wolf,
  Fox,
  Bear,
  Panda,
  Koala,
  Lion,
  Tiger,
  Leopard,
  Elephant,
  Rhino,
  Hippo,
  Giraffe,
  Zebra,
  Horse,
  Cow,
  Pig,
  Sheep,
  Goat,
  Chicken,
  Rooster,
  Duck,
  Goose,
  Turkey,
  Peacock,
  Owl,
  Eagle,
  Hawk,
  Parrot,
  Penguin,
  Flamingo,
  Swan,
  Crane,
  Stork,
  Pelican,
  Seagull,
  Dove,
  Raven,
  Crow,
  Sparrow,
  Robin,
  Cardinal,
  Bluebird,
  Canary,
  Finch,
  Hummingbird,
  Woodpecker,
  Kingfisher,
  Toucan,
  Ostrich,
  Emu,
  Kiwi,
  Dodo,
  Dinosaur,
  Dragon,
  Unicorn,
  Phoenix,
  Pegasus,
  Centaur,
  Mermaid,
  Fairy,
  Angel,
  Devil,
  Ghost,
  Zombie,
  Vampire,
  Werewolf,
  Witch,
  Wizard,
  Mage,
  Knight,
  Warrior,
  Archer,
  Assassin,
  Thief,
  Rogue,
  Paladin,
  Cleric,
  Monk,
  Barbarian,
  Ranger,
  Druid,
  Sorcerer,
  Warlock,
  Bard,
  Artificer,
  Alchemist,
  Blacksmith,
  Carpenter,
  Mason,
  Tailor,
  Baker,
  Chef,
  Farmer,
  Fisherman,
  Hunter,
  Miner,
  Lumberjack,
  Merchant,
  Trader,
  Banker,
  Lawyer,
  Judge,
  Police,
  Firefighter,
  Doctor,
  Nurse,
  Teacher,
  Student,
  Scientist,
  Engineer,
  Architect,
  Artist,
  Musician,
  Writer,
  Poet,
  Actor,
  Dancer,
  Singer,
  Comedian,
  Magician,
  Acrobat,
  Athlete,
  Runner,
  Swimmer,
  Cyclist,
  Skier,
  Snowboarder,
  Surfer,
  Skater,
  Climber,
  Hiker,
  Camper,
  Explorer,
  Adventurer,
  Traveler,
  Tourist,
  Pilgrim,
  Nomad,
  Wanderer,
  Drifter,
  Vagrant,
  Hermit,
  Monk as MonkIcon,
  Nun,
  Priest,
  Pastor,
  Rabbi,
  Imam,
  Shaman,
  Oracle,
  Prophet,
  Sage,
  Guru,
  Master,
  Sensei,
  Mentor,
  Leader,
  Chief,
  King,
  Queen,
  Prince,
  Princess,
  Duke,
  Duchess,
  Earl,
  Countess,
  Baron,
  Baroness,
  Lord,
  Lady,
  Sir,
  Dame,
  Knight as KnightIcon,
  Squire,
  Page,
  Herald,
  Messenger,
  Ambassador,
  Diplomat,
  Spy,
  Agent,
  Detective,
  Inspector,
  Investigator,
  Sleuth,
  Sherlock,
  Watson,
  Holmes,
  Poirot,
  Columbo,
  Monk as MonkDetective,
  Psych,
  Castle,
  Bones,
  CSI,
  NCIS,
  FBI,
  CIA,
  NSA,
  MI6,
  KGB,
  Mossad,
  Interpol,
  Scotland,
  Yard,
  Police as PoliceIcon,
  Sheriff,
  Marshal,
  Ranger as RangerIcon,
  Trooper,
  Officer,
  Sergeant,
  Lieutenant,
  Captain,
  Major,
  Colonel,
  General,
  Admiral,
  Commander,
  Commodore,
  Captain as CaptainIcon,
  Lieutenant as LieutenantIcon,
  Ensign,
  Midshipman,
  Cadet,
  Recruit,
  Soldier,
  Marine,
  Sailor,
  Airman,
  Pilot,
  Navigator,
  Engineer as EngineerIcon,
  Mechanic,
  Technician,
  Specialist,
  Expert,
  Professional,
  Amateur,
  Novice,
  Beginner,
  Apprentice,
  Journeyman,
  Craftsman,
  Artisan,
  Artist as ArtistIcon,
  Creator,
  Maker,
  Builder,
  Designer,
  Developer,
  Programmer,
  Coder,
  Hacker,
  Geek,
  Nerd,
  Genius,
  Prodigy,
  Savant,
  Virtuoso,
  Maestro,
  Virtuoso as VirtuosoIcon,
  Legend,
  Icon,
  Celebrity,
  Famous,
  Popular,
  Trending,
  Viral,
  Meme,
  Joke,
  Funny,
  Hilarious,
  Comedy,
  Humor,
  Wit,
  Sarcasm,
  Irony,
  Satire,
  Parody,
  Mockery,
  Ridicule,
  Scorn,
  Contempt,
  Disdain,
  Disgust,
  Revulsion,
  Repulsion,
  Aversion,
  Hatred,
  Loathing,
  Abhorrence,
  Detestation,
  Animosity,
  Hostility,
  Enmity,
  Antagonism,
  Opposition,
  Resistance,
  Defiance,
  Rebellion,
  Revolution,
  Uprising,
  Revolt,
  Mutiny,
  Insurrection,
  Coup,
  Overthrow,
  Takeover,
  Conquest,
  Victory,
  Triumph,
  Success,
  Achievement,
  Accomplishment,
  Attainment,
  Fulfillment,
  Realization,
  Completion,
  Finish,
  End,
  Conclusion,
  Finale,
  Climax,
  Peak,
  Summit,
  Top,
  Apex,
  Pinnacle,
  Zenith,
  Acme,
  Maximum,
  Limit,
  Boundary,
  Border,
  Edge,
  Margin,
  Perimeter,
  Circumference,
  Radius,
  Diameter,
  Center,
  Middle,
  Core,
  Heart,
  Soul,
  Spirit,
  Essence,
  Nature,
  Character,
  Personality,
  Identity,
  Self,
  Individual,
  Person,
  Human,
  Being,
  Creature,
  Entity,
  Existence,
  Life,
  Living,
  Alive,
  Breathing,
  Conscious,
  Aware,
  Awake,
  Alert,
  Vigilant,
  Watchful,
  Observant,
  Attentive,
  Focused,
  Concentrated,
  Intense,
  Serious,
  Grave,
  Solemn,
  Somber,
  Grim,
  Dark,
  Black,
  White,
  Gray,
  Grey,
  Silver,
  Gold,
  Bronze,
  Copper,
  Iron,
  Steel,
  Metal,
  Stone,
  Rock,
  Crystal,
  Diamond,
  Ruby,
  Emerald,
  Sapphire,
  Pearl,
  Amber,
  Jade,
  Opal,
  Turquoise,
  Amethyst,
  Topaz,
  Garnet,
  Onyx,
  Obsidian,
  Quartz,
  Granite,
  Marble,
  Limestone,
  Sandstone,
  Slate,
  Shale,
  Clay,
  Sand,
  Dirt,
  Soil,
  Earth,
  Ground,
  Land,
  Terrain,
  Landscape,
  Scenery,
  View,
  Sight,
  Scene,
  Picture,
  Image as ImageFinal,
  Photo,
  Photograph,
  Snapshot,
  Portrait,
  Selfie,
  Headshot,
  Closeup,
  Wideshot,
  Panorama,
  Landscape as LandscapeIcon,
  Seascape,
  Cityscape,
  Skyline,
  Horizon,
  Sunset,
  Sunrise,
  Dawn,
  Dusk,
  Twilight,
  Night,
  Day,
  Morning,
  Afternoon,
  Evening,
  Midnight,
  Noon,
  Time,
  Clock,
  Watch,
  Timer,
  Stopwatch,
  Alarm,
  Calendar,
  Date,
  Schedule,
  Appointment,
  Meeting,
  Conference,
  Seminar,
  Workshop,
  Class,
  Lesson,
  Tutorial,
  Guide,
  Manual,
  Handbook,
  Book,
  Novel,
  Story,
  Tale,
  Narrative,
  Account,
  Report,
  Article,
  Essay,
  Paper,
  Document,
  File,
  Record,
  Log,
  Journal,
  Diary,
  Notebook,
  Notepad,
  Memo,
  Note,
  Message,
  Letter,
  Mail,
  Email,
  Text,
  SMS,
  Chat,
  Conversation,
  Discussion,
  Dialogue,
  Talk,
  Speech,
  Presentation,
  Lecture,
  Sermon,
  Monologue,
  Soliloquy,
  Aside,
  Whisper,
  Shout,
  Scream,
  Yell,
  Cry,
  Weep,
  Sob,
  Wail,
  Moan,
  Groan,
  Sigh,
  Gasp,
  Pant,
  Breathe,
  Inhale,
  Exhale,
  Blow,
  Suck,
  Kiss,
  Hug,
  Embrace,
  Hold,
  Grasp,
  Grip,
  Clutch,
  Squeeze,
  Press,
  Push,
  Pull,
  Drag,
  Lift,
  Carry,
  Transport,
  Shift,
  Transfer,
  Relocate,
  Migrate,
  Travel,
  Journey,
  Trip,
  Voyage,
  Expedition,
  Adventure,
  Quest,
  Mission,
  Task,
  Job,
  Work,
  Labor,
  Effort,
  Struggle,
  Fight,
  Battle,
  War,
  Conflict,
  Dispute,
  Argument,
  Debate,
  Discussion as DiscussionIcon,
  Negotiation,
  Compromise,
  Agreement,
  Deal,
  Contract,
  Pact,
  Treaty,
  Alliance,
  Partnership,
  Collaboration,
  Cooperation,
  Teamwork,
  Unity,
  Harmony,
  Peace,
  Tranquility,
  Serenity,
  Calm,
  Quiet,
  Silence,
  Still,
  Motionless,
  Static,
  Fixed,
  Stable,
  Steady,
  Constant,
  Consistent,
  Regular,
  Normal,
  Ordinary,
  Common,
  Usual,
  Typical,
  Standard,
  Average,
  Medium,
  Moderate,
  Mild,
  Gentle,
  Soft,
  Smooth,
  Rough,
  Hard,
  Tough,
  Strong,
  Powerful,
  Mighty,
  Robust,
  Sturdy,
  Solid,
  Firm,
  Rigid,
  Stiff,
  Flexible,
  Elastic,
  Stretchy,
  Bouncy,
  Springy,
  Resilient,
  Durable,
  Lasting,
  Permanent,
  Eternal,
  Forever,
  Always,
  Never,
  Sometimes,
  Often,
  Rarely,
  Seldom,
  Occasionally,
  Frequently,
  Regularly,
  Daily,
  Weekly,
  Monthly,
  Yearly,
  Annual,
  Seasonal,
  Periodic,
  Cyclical,
  Repetitive,
  Recurring,
  Continuous,
  Ongoing,
  Persistent,
  Enduring,
  Lasting as LastingIcon,
  Temporary,
  Brief,
  Short,
  Quick,
  Fast,
  Rapid,
  Swift,
  Speedy,
  Hasty,
  Hurried,
  Rushed,
  Urgent,
  Emergency,
  Crisis,
  Disaster,
  Catastrophe,
  Tragedy,
  Misfortune,
  Accident,
  Incident,
  Event,
  Occurrence,
  Happening,
  Situation,
  Circumstance,
  Condition,
  State,
  Status,
  Position,
  Location,
  Place,
  Spot,
  Point,
  Area,
  Region,
  Zone,
  District,
  Neighborhood,
  Community,
  Society,
  Culture,
  Civilization,
  Nation,
  Country,
  State as StateIcon,
  Province,
  Territory,
  Colony,
  Empire,
  Kingdom,
  Republic,
  Democracy,
  Government,
  Politics,
  Policy,
  Law,
  Rule,
  Regulation,
  Order,
  Command,
  Instruction,
  Direction,
  Guidance,
  Advice,
  Suggestion,
  Recommendation,
  Proposal,
  Idea,
  Concept,
  Notion,
  Thought,
  Mind,
  Brain,
  Intelligence,
  Wisdom,
  Knowledge,
  Information,
  Data,
  Facts,
  Truth,
  Reality,
  Actuality,
  Existence as ExistenceIcon,
  Being as BeingIcon,
  Life as LifeIcon,
  Death,
  Birth,
  Beginning,
  Start,
  Origin,
  Source,
  Root,
  Foundation,
  Base,
  Bottom,
  Floor,
  Ground as GroundIcon,
  Surface,
  Top as TopIcon,
  Ceiling,
  Roof,
  Sky,
  Heaven,
  Paradise,
  Hell,
  Underworld,
  Abyss,
  Void,
  Nothing,
  Empty,
  Blank,
  Clear,
  Transparent,
  Invisible,
  Hidden,
  Secret,
  Mystery,
  Puzzle,
  Riddle,
  Enigma,
  Question,
  Answer,
  Solution,
  Problem,
  Issue,
  Matter,
  Subject,
  Topic,
  Theme,
  Category,
  Kind,
  Sort,
  Variety,
  Diversity,
  Difference,
  Distinction,
  Comparison,
  Similarity,
  Likeness,
  Resemblance,
  Analogy,
  Metaphor,
  Symbol,
  Sign,
  Signal,
  Indicator,
  Marker,
  Label,
  Tag,
  Badge,
  Emblem,
  Logo,
  Brand,
  Name,
  Title,
  Heading,
  Header,
  Footer,
  Sidebar,
  Menu,
  Navigation as NavigationIcon,
  Connection,
  Relationship,
  Association,
  Bond,
  Tie,
  Attachment,
  Affection,
  Love,
  Passion,
  Desire,
  Want,
  Need,
  Requirement,
  Necessity,
  Essential,
  Important,
  Significant,
  Meaningful,
  Valuable,
  Precious,
  Rare,
  Unique,
  Special,
  Extraordinary,
  Amazing,
  Wonderful,
  Fantastic,
  Incredible,
  Unbelievable,
  Impossible,
  Possible,
  Probable,
  Likely,
  Unlikely,
  Certain,
  Sure,
  Definite,
  Absolute,
  Complete,
  Total,
  Whole,
  Entire,
  Full,
  Partial,
  Incomplete,
  Unfinished,
  Ongoing as OngoingIcon,
  Progress,
  Development,
  Growth,
  Expansion,
  Increase,
  Decrease,
  Reduction,
  Decline,
  Fall,
  Drop,
  Rise,
  Climb,
  Ascent,
  Descent,
  Up,
  Down,
  Left,
  Right,
  Forward,
  Backward,
  Ahead,
  Behind,
  Before,
  After,
  During,
  While,
  When,
  Where,
  Why,
  How,
  What,
  Who,
  Which,
  Whose,
  Whom,
  This,
  That,
  These,
  Those,
  Here,
  There,
  Everywhere,
  Nowhere,
  Somewhere,
  Anywhere,
  Everyone,
  Nobody,
  Somebody,
  Anybody,
  Everything,
  Something,
  Anything,
  All,
  None,
  Some,
  Any,
  Many,
  Few,
  Several,
  Various,
  Different,
  Same,
  Similar,
  Identical,
  Equivalent,
  Comparable,
  Relative,
  Absolute as AbsoluteIcon,
  Perfect,
  Flawless,
  Ideal,
  Best,
  Worst,
  Better,
  Worse,
  Good,
  Bad,
  Great,
  Terrible,
  Excellent,
  Poor,
  High,
  Low,
  Big,
  Small,
  Large,
  Tiny,
  Huge,
  Massive,
  Giant,
  Enormous,
  Immense,
  Vast,
  Wide,
  Narrow,
  Broad,
  Thin,
  Thick,
  Fat,
  Skinny,
  Slim,
  Lean,
  Heavy,
  Light,
  Dense,
  Sparse,
  Crowded,
  Empty as EmptyIcon,
  Full as FullIcon,
  Packed,
  Stuffed,
  Filled,
  Loaded,
  Charged,
  Powered,
  Energized,
  Active,
  Passive,
  Inactive,
  Dormant,
  Sleeping,
  Awake as AwakeIcon,
  Alert as AlertIcon,
  Aware as AwareIcon,
  Conscious as ConsciousIcon,
  Unconscious,
  Subconscious,
  Automatic,
  Mechanical,
  Electronic,
  Digital,
  Analog,
  Virtual,
  Real,
  Actual,
  Fake,
  False,
  True,
  Correct,
  Wrong,
  Left as LeftIcon,
  Straight,
  Curved,
  Bent,
  Twisted,
  Turned,
  Rotated,
  Flipped,
  Reversed,
  Inverted,
  Upside,
  Downside,
  Inside,
  Outside,
  Interior,
  Exterior,
  Internal,
  External,
  Public,
  Private,
  Personal,
  Individual as IndividualIcon,
  Collective,
  Group,
  Team,
  Organization,
  Company,
  Business,
  Enterprise,
  Corporation,
  Agency,
  Institution,
  Establishment,
  Foundation as FoundationIcon,
  Association as AssociationIcon,
  Society as SocietyIcon,
  Community as CommunityIcon,
  Network,
  System,
  Structure,
  Framework,
  Architecture,
  Design as DesignIcon,
  Plan,
  Strategy,
  Tactic,
  Method,
  Technique,
  Approach,
  Way,
  Manner,
  Style,
  Fashion,
  Trend,
  Pattern,
  Model,
  Template,
  Format,
  Layout,
  Arrangement,
  Organization as OrganizationIcon,
  Order as OrderIcon,
  Sequence,
  Series,
  Chain,
  Line,
  Row,
  Column,
  List,
  Array,
  Matrix,
  Table,
  Chart,
  Graph,
  Diagram,
  Map as MapIcon,
  Blueprint,
  Sketch,
  Drawing,
  Painting,
  Artwork,
  Masterpiece,
  Creation,
  Invention,
  Innovation,
  Discovery,
  Finding,
  Result,
  Outcome,
  Consequence,
  Effect,
  Impact,
  Influence,
  Power,
  Force,
  Energy,
  Strength,
  Weakness,
  Advantage,
  Disadvantage,
  Benefit,
  Drawback,
  Pro,
  Con,
  Plus,
  Minus,
  Positive,
  Negative,
  Neutral,
  Balanced,
  Unbalanced,
  Stable as StableIcon,
  Unstable,
  Secure,
  Insecure,
  Safe,
  Dangerous,
  Risky,
  Hazardous,
  Harmful,
  Beneficial,
  Useful,
  Useless,
  Helpful,
  Unhelpful,
  Effective,
  Ineffective,
  Efficient,
  Inefficient,
  Productive,
  Unproductive,
  Successful,
  Unsuccessful,
  Winning,
  Losing,
  Victory as VictoryIcon,
  Defeat,
  Loss,
  Gain,
  Profit,
  Loss as LossIcon,
  Cost,
  Price,
  Value,
  Worth,
  Quality,
  Quantity,
  Amount,
  Number,
  Count,
  Total as TotalIcon,
  Sum,
  Average as AverageIcon,
  Mean,
  Median,
  Mode,
  Range,
  Minimum,
  Maximum as MaximumIcon,
  Limit as LimitIcon,
  Boundary as BoundaryIcon,
  Border as BorderIcon,
  Edge as EdgeIcon,
  Corner,
  Side,
  Face,
  Surface as SurfaceIcon,
  Area as AreaIcon,
  Volume,
  Capacity,
  Size,
  Dimension,
  Length,
  Width,
  Height,
  Depth,
  Distance,
  Space,
  Room,
  Place as PlaceIcon,
  Position as PositionIcon,
  Location as LocationIcon,
  Spot as SpotIcon,
  Point as PointIcon,
  Coordinate,
  Address,
  Direction as DirectionIcon,
  Path,
  Route,
  Road,
  Street,
  Avenue,
  Boulevard,
  Lane,
  Alley,
  Highway,
  Freeway,
  Bridge,
  Tunnel,
  Intersection,
  Junction,
  Crossroad,
  Corner as CornerIcon,
  Turn,
  Curve,
  Bend,
  Twist,
  Loop,
  Circle as CircleIcon,
  Square as SquareIcon,
  Triangle as TriangleIcon,
  Rectangle,
  Oval,
  Ellipse,
  Polygon,
  Pentagon,
  Hexagon,
  Octagon,
  Star as StarIcon,
  Diamond as DiamondIcon,
  Heart as HeartIcon,
  Spade,
  Club,
  Cross,
  Plus as PlusIcon,
  Minus as MinusIcon,
  Multiply,
  Divide,
  Equal,
  Greater,
  Less,
  Percent,
  Fraction,
  Decimal,
  Integer,
  Number as NumberIcon,
  Digit,
  Figure,
  Numeral,
  Symbol as SymbolIcon,
  Word,
  Sentence,
  Paragraph,
  Chapter,
  Section,
  Part,
  Piece,
  Fragment,
  Portion,
  Share,
  Division,
  Unit,
  Component,
  Element,
  Item,
  Object,
  Thing,
  Stuff,
  Material,
  Substance,
  Matter as MatterIcon,
  Content,
  Information as InformationIcon,
  Data as DataIcon,
  Knowledge as KnowledgeIcon,
  Wisdom as WisdomIcon,
  Intelligence as IntelligenceIcon,
  Understanding,
  Comprehension,
  Awareness,
  Consciousness,
  Perception,
  Sensation,
  Feeling,
  Emotion,
  Mood,
  Attitude,
  Opinion,
  Belief,
  Faith,
  Trust,
  Confidence,
  Doubt,
  Uncertainty,
  Confusion,
  Clarity,
  Understanding as UnderstandingIcon,
  Misunderstanding,
  Agreement as AgreementIcon,
  Disagreement,
  Consensus,
  Conflict as ConflictIcon,
  Harmony as HarmonyIcon,
  Discord,
  Peace as PeaceIcon,
  War as WarIcon,
  Battle as BattleIcon,
  Fight as FightIcon,
  Struggle as StruggleIcon,
  Competition,
  Contest,
  Match,
  Game,
  Sport,
  Fun,
  CheckCircle,
  Copy,
  EyeOff,
  Trash2,
  ArrowRight,
  Entertainment,
  Amusement,
  Enjoyment,
  Pleasure,
  Happiness,
  Joy,
  Delight,
  Satisfaction,
  Contentment,
  Fulfillment as FulfillmentIcon,
  Achievement as AchievementIcon,
  Success as SuccessIcon,
  Accomplishment as AccomplishmentIcon,
  Goal,
  Objective,
  Target as TargetIcon,
  Aim,
  Purpose,
  Intention,
  Plan as PlanIcon,
  Strategy as StrategyIcon,
  Scheme,
  Plot,
  Design as DesignFinal,
  Blueprint as BlueprintIcon,
  Draft,
  Outline,
  Summary,
  Overview,
  Introduction,
  Conclusion as ConclusionIcon,
  End as EndIcon,
  Finish as FinishIcon,
  Complete as CompleteIcon,
  Done,
  Ready,
  Prepared,
  Set,
  Go,
  Start as StartIcon,
  Begin,
  Commence,
  Initiate,
  Launch,
  Open,
  Close,
  Shut,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  Password,
  Code as CodeIcon,
  Cipher,
  Encryption,
  Decryption,
  Security,
  Protection,
  Defense,
  Guard,
  Shield as ShieldIcon,
  Armor,
  Barrier,
  Wall,
  Fence,
  Gate,
  Door,
  Window,
  Opening,
  Entrance,
  Exit,
  Way as WayIcon,
  Path as PathIcon,
  Route as RouteIcon,
  Journey as JourneyIcon,
  Trip as TripIcon,
  Travel as TravelIcon,
  Transport as TransportIcon,
  Vehicle,
  Car as CarIcon,
  Truck as TruckIcon,
  Bus as BusIcon,
  Train as TrainIcon,
  Plane as PlaneIcon,
  Ship as ShipIcon,
  Boat,
  Yacht,
  Sailboat,
  Speedboat,
  Submarine,
  Helicopter,
  Jet,
  Rocket,
  Spaceship,
  UFO,
  Alien,
  Robot,
  Android,
  Cyborg,
  Machine,
  Computer,
  Laptop,
  Desktop,
  Tablet,
  Phone,
  Smartphone as SmartphoneIcon,
  Mobile,
  Device,
  Gadget,
  Tool,
  Instrument,
  Equipment,
  Apparatus,
  Machinery,
  Technology,
  Innovation as InnovationIcon,
  Invention as InventionIcon,
  Discovery as DiscoveryIcon,
  Research,
  Study,
  Investigation,
  Exploration,
  Experiment,
  Test,
  Trial,
  Attempt,
  Try,
  Effort as EffortIcon,
  Work as WorkIcon,
  Job as JobIcon,
  Task as TaskIcon,
  Assignment,
  Project,
  Mission as MissionIcon,
  Quest as QuestIcon,
  Adventure as AdventureIcon,
  Journey as JourneyFinal,
  Experience,
  Memory,
  Remembrance,
  Recollection,
  Recall,
  Recognition,
  Identification,
  Classification,
  Categorization,
  Organization as OrganizationFinal,
  Arrangement as ArrangementIcon,
  Structure as StructureIcon,
  System as SystemIcon,
  Network as NetworkIcon,
  Connection as ConnectionIcon,
  Link as LinkIcon,
  Relationship as RelationshipIcon,
  Association as AssociationFinal,
  Partnership as PartnershipIcon,
  Collaboration as CollaborationIcon,
  Cooperation as CooperationIcon,
  Teamwork as TeamworkIcon,
  Unity as UnityIcon,
  Together,
  Apart,
  Separate,
  Individual as IndividualFinal,
  Alone,
  Solo,
  Single,
  One,
  Two,
  Three,
  Four,
  Five,
  Six,
  Seven,
  Eight,
  Nine,
  Ten,
  Eleven,
  Twelve,
  Thirteen,
  Fourteen,
  Fifteen,
  Sixteen,
  Seventeen,
  Eighteen,
  Nineteen,
  Twenty,
  Thirty,
  Forty,
  Fifty,
  Sixty,
  Seventy,
  Eighty,
  Ninety,
  Hundred,
  Thousand,
  Million,
  Billion,
  Trillion,
  Infinity,
  Zero,
  First,
  Second,
  Third,
  Fourth,
  Fifth,
  Sixth,
  Seventh,
  Eighth,
  Ninth,
  Tenth,
  Last,
  Final,
  Ultimate,
  Best as BestIcon,
  Worst as WorstIcon,
  Top as TopFinal,
  Bottom as BottomIcon,
  High as HighIcon,
  Low as LowIcon,
  Up as UpIcon,
  Down as DownIcon,
  Left as LeftFinal,
  Right as RightIcon,
  Center as CenterIcon,
  Middle as MiddleIcon,
  Side as SideIcon,
  Corner as CornerFinal,
  Edge as EdgeFinal,
  Border as BorderFinal,
  Boundary as BoundaryFinal,
  Limit as LimitFinal,
  Range as RangeIcon,
  Scope,
  Scale,
  Measure,
  Metric,
  Standard as StandardIcon,
  Norm,
  Rule as RuleIcon,
  Law as LawIcon,
  Regulation as RegulationIcon,
  Policy as PolicyIcon,
  Procedure,
  Process,
  Method as MethodIcon,
  Technique as TechniqueIcon,
  Approach as ApproachIcon,
  Strategy as StrategyFinal,
  Plan as PlanFinal,
  Scheme as SchemeIcon,
  Design as DesignUltimate,
  Pattern as PatternIcon,
  Template as TemplateIcon,
  Model as ModelIcon,
  Example,
  Sample,
  Instance,
  Case,
  Situation as SituationIcon,
  Scenario,
  Context,
  Environment,
  Setting,
  Background,
  Foreground,
  Focus as FocusIcon,
  Attention,
  Concentration,
  Intensity,
  Strength as StrengthIcon,
  Power as PowerIcon,
  Force as ForceIcon,
  Energy as EnergyIcon,
  Momentum,
  Speed as SpeedIcon,
  Velocity,
  Acceleration,
  Deceleration,
  Motion,
  Movement,
  Action,
  Behavior,
  Conduct,
  Performance,
  Execution,
  Implementation,
  Application,
  Usage,
  Use,
  Utilization,
  Employment,
  Operation,
  Function,
  Purpose as PurposeIcon,
  Role,
  Responsibility,
  Duty,
  Obligation,
  Commitment,
  Promise,
  Pledge,
  Vow,
  Oath,
  Statement,
  Declaration,
  Announcement,
  Proclamation,
  Notice,
  Warning,
  Alert as AlertFinal,
  Alarm as AlarmIcon,
  Signal as SignalIcon,
  Sign as SignIcon,
  Symbol as SymbolFinal,
  Icon as IconFinal,
  Image as ImageUltimate,
} from "lucide-react";

const ImageTools: React.FC = () => {
  const toolCategories = [
    {
      title: "Basic Editing",
      icon: Scissors,
      color: "green",
      description: "Essential image editing tools for everyday use",
      tools: [
        {
          name: "Crop Image",
          path: "/en-US/tool/image-crop",
          icon: Crop,
          description:
            "Crop images to custom or preset sizes with precision guides",
        },
        {
          name: "Resize Image",
          path: "/en-US/tool/image-resize",
          icon: Resize,
          description:
            "Resize images while maintaining quality with AI upscaling",
        },
        {
          name: "Rotate & Flip",
          path: "/en-US/tool/image-rotate",
          icon: RotateCw,
          description: "Rotate and flip images with custom angle controls",
        },
        {
          name: "Brightness & Contrast",
          path: "/en-US/tool/image-adjust",
          icon: Sun,
          description: "Adjust brightness, contrast, and exposure levels",
        },
        {
          name: "Color Balance",
          path: "/en-US/tool/color-balance",
          icon: Palette,
          description: "Fine-tune color temperature and saturation",
        },
        {
          name: "Sharpen & Blur",
          path: "/en-US/tool/image-filter",
          icon: Focus,
          description: "Apply sharpening or blur effects with precision",
        },
        {
          name: "Auto Enhance",
          path: "/en-US/tool/auto-enhance",
          icon: Wand2,
          description: "One-click automatic image enhancement",
        },
        {
          name: "Perspective Correct",
          path: "/en-US/tool/perspective-correct",
          icon: Move,
          description: "Fix perspective distortion and keystone effects",
        },
      ],
    },

    {
      title: "Photo Restoration",
      icon: Sparkles,
      color: "blue",
      description: "Restore and repair damaged or old photographs",
      tools: [
        {
          name: "Restore Old Photos",
          path: "/en-US/tool/photo-restore",
          icon: Camera,
          description: "Repair scratches, tears, and fading in vintage photos",
        },
        {
          name: "Unblur Images",
          path: "/en-US/tool/image-unblur",
          icon: Eye,
          description: "Sharpen blurry images using deconvolution algorithms",
        },
        {
          name: "Remove Scratches",
          path: "/en-US/tool/scratch-remove",
          icon: Eraser,
          description: "Automatically detect and remove scratches and dust",
        },
        {
          name: "Color Restoration",
          path: "/en-US/tool/color-restore",
          icon: Droplets,
          description: "Restore faded colors in old photographs",
        },
      ],
    },
    {
      title: "Creative Effects",
      icon: Palette,
      color: "pink",
      description: "Artistic filters and creative image transformations",
      tools: [
        {
          name: "Artistic Filters",
          path: "/en-US/tool/artistic-filters",
          icon: Brush,
          description: "Oil painting, watercolor, and sketch effects",
        },
        {
          name: "Vintage Effects",
          path: "/en-US/tool/vintage-effects",
          icon: Camera,
          description: "Retro film looks and vintage color grading",
        },
        {
          name: "HDR Effects",
          path: "/en-US/tool/hdr-effects",
          icon: Sun,
          description: "High dynamic range tone mapping effects",
        },
        {
          name: "Black & White",
          path: "/en-US/tool/black-white",
          icon: Moon,
          description: "Professional B&W conversion with channel mixing",
        },
        {
          name: "Sepia Toning",
          path: "/en-US/tool/sepia-tone",
          icon: Droplets,
          description: "Classic sepia and duotone effects",
        },
        {
          name: "Cross Processing",
          path: "/en-US/tool/cross-process",
          icon: RefreshCw,
          description: "Film cross-processing color effects",
        },
        {
          name: "Lomography",
          path: "/en-US/tool/lomography",
          icon: Camera,
          description: "Lomo camera effects with vignetting",
        },
        {
          name: "Orton Effect",
          path: "/en-US/tool/orton-effect",
          icon: Sparkles,
          description: "Dreamy glow effect for landscapes",
        },
      ],
    },
    {
      title: "Design & Graphics",
      icon: Layers,
      color: "indigo",
      description: "Professional design tools and graphic elements",
      tools: [
        {
          name: "Add Text",
          path: "/en-US/tool/add-text",
          icon: Type,
          description: "Add text with custom fonts, effects, and styling",
        },
        {
          name: "Logo Maker",
          path: "/en-US/tool/logo-maker",
          icon: Star,
          description: "Create professional logos with templates",
        },
        {
          name: "Watermark Tool",
          path: "/en-US/tool/watermark",
          icon: Stamp,
          description: "Add text or image watermarks with transparency",
        },
        {
          name: "Border & Frames",
          path: "/en-US/tool/borders-frames",
          icon: Square,
          description: "Add decorative borders and photo frames",
        },
        {
          name: "Shape Overlays",
          path: "/en-US/tool/shape-overlays",
          icon: Shapes,
          description: "Add geometric shapes and design elements",
        },
        {
          name: "Gradient Maker",
          path: "/en-US/tool/gradient-maker",
          icon: Blend,
          description: "Create and apply custom gradient overlays",
        },
        {
          name: "Pattern Fill",
          path: "/en-US/tool/pattern-fill",
          icon: Grid,
          description: "Fill areas with patterns and textures",
        },
        {
          name: "Shadow Effects",
          path: "/en-US/tool/shadow-effects",
          icon: Layers,
          description: "Add drop shadows and 3D effects",
        },
      ],
    },
    {
      title: "Photo Collage",
      icon: Grid,
      color: "teal",
      description: "Create stunning photo collages and layouts",
      tools: [
        {
          name: "Collage Maker",
          path: "/en-US/tool/collage-maker",
          icon: Grid,
          description: "Create photo collages with customizable layouts",
        },
        {
          name: "Photo Grid",
          path: "/en-US/tool/photo-grid",
          icon: Grid,
          description: "Arrange photos in perfect grid layouts",
        },
        {
          name: "Mosaic Creator",
          path: "/en-US/tool/mosaic-creator",
          icon: Grid,
          description: "Create photo mosaics from multiple images",
        },
        {
          name: "Panorama Maker",
          path: "/en-US/tool/panorama-maker",
          icon: Maximize2,
          description: "Stitch multiple photos into panoramas",
        },
        {
          name: "Before/After",
          path: "/en-US/tool/before-after",
          icon: FlipHorizontal,
          description: "Create before and after comparison images",
        },
        {
          name: "Photo Strips",
          path: "/en-US/tool/photo-strips",
          icon: Layers,
          description: "Create photo booth style strips",
        },
        {
          name: "Scrapbook",
          path: "/en-US/tool/scrapbook",
          icon: Heart,
          description: "Design scrapbook pages with decorative elements",
        },
        {
          name: "Timeline Maker",
          path: "/en-US/tool/timeline-maker",
          icon: Calendar,
          description: "Create visual timelines with photos",
        },
      ],
    },
    {
      title: "Format Conversion",
      icon: RefreshCw,
      color: "orange",
      description: "Convert between image formats and optimize files",
      tools: [
        {
          name: "Format Converter",
          path: "/en-US/tool/image-converter",
          icon: RefreshCw,
          description: "Convert between JPG, PNG, WEBP, SVG, and more",
        },
        {
          name: "Batch Convert",
          path: "/en-US/tool/batch-convert",
          icon: Layers,
          description: "Convert multiple images simultaneously",
        },
        {
          name: "Compress Images",
          path: "/en-US/tool/image-compress",
          icon: Archive,
          description: "Reduce file size without visible quality loss",
        },
        {
          name: "WebP Converter",
          path: "/en-US/tool/webp-converter",
          icon: Zap,
          description: "Convert to modern WebP format for web",
        },
        {
          name: "HEIC Converter",
          path: "/en-US/tool/heic-converter",
          icon: Smartphone,
          description: "Convert iPhone HEIC photos to JPG/PNG",
        },
        {
          name: "RAW Processor",
          path: "/en-US/tool/raw-processor",
          icon: Camera,
          description: "Process and convert RAW camera files",
        },
        {
          name: "Vector Converter",
          path: "/en-US/tool/vector-converter",
          icon: Layers,
          description: "Convert raster images to vector formats",
        },
        {
          name: "PDF to Image",
          path: "/en-US/tool/pdf-to-image",
          icon: FileText,
          description: "Extract images from PDF documents",
        },
      ],
    },
    {
      title: "Professional Tools",
      icon: Sliders,
      color: "red",
      description: "Advanced tools for professional photographers",
      tools: [
        {
          name: "Curves Adjustment",
          path: "/en-US/tool/curves-adjust",
          icon: TrendingUp,
          description: "Professional tone curve adjustments",
        },
        {
          name: "Levels Correction",
          path: "/en-US/tool/levels-correct",
          icon: BarChart,
          description: "Histogram-based exposure correction",
        },
        {
          name: "Color Grading",
          path: "/en-US/tool/color-grading",
          icon: Palette,
          description: "Professional color grading and LUTs",
        },
        {
          name: "Lens Correction",
          path: "/en-US/tool/lens-correct",
          icon: Aperture,
          description: "Fix barrel distortion and vignetting",
        },
        {
          name: "Chromatic Aberration",
          path: "/en-US/tool/chromatic-fix",
          icon: Focus,
          description: "Remove color fringing and aberrations",
        },
        {
          name: "White Balance",
          path: "/en-US/tool/white-balance",
          icon: Sun,
          description: "Correct color temperature and tint",
        },
        {
          name: "Exposure Blend",
          path: "/en-US/tool/exposure-blend",
          icon: Layers,
          description: "Blend multiple exposures for HDR",
        },
        {
          name: "Focus Stacking",
          path: "/en-US/tool/focus-stack",
          icon: Target,
          description: "Combine multiple focus points for sharp images",
        },
      ],
    },
    {
      title: "Measurement & Analysis",
      icon: Gauge,
      color: "gray",
      description: "Analyze and measure image properties",
      tools: [
        {
          name: "Color Picker",
          path: "/en-US/tool/color-picker",
          icon: Palette,
          description: "Extract colors and create palettes from images",
        },
        {
          name: "Histogram Viewer",
          path: "/en-US/tool/histogram",
          icon: BarChart,
          description: "Analyze RGB and luminance histograms",
        },
        {
          name: "EXIF Viewer",
          path: "/en-US/tool/exif-viewer",
          icon: Eye,
          description: "View detailed image metadata and camera settings",
        },
        {
          name: "Pixel Inspector",
          path: "/en-US/tool/pixel-inspector",
          icon: Crosshair,
          description: "Examine individual pixel values and coordinates",
        },
        {
          name: "Image Dimensions",
          path: "/en-US/tool/image-dimensions",
          icon: Maximize2,
          description: "Measure and display image dimensions",
        },
        {
          name: "Color Space Info",
          path: "/en-US/tool/color-space",
          icon: Palette,
          description: "Analyze color space and profile information",
        },
        {
          name: "Quality Assessment",
          path: "/en-US/tool/quality-assess",
          icon: CheckCircle,
          description: "Analyze image quality and sharpness",
        },
        {
          name: "Duplicate Finder",
          path: "/en-US/tool/duplicate-finder",
          icon: Copy,
          description: "Find and remove duplicate images",
        },
      ],
    },
    {
      title: "Specialized Tools",
      icon: Cpu,
      color: "violet",
      description: "Specialized tools for specific use cases",
      tools: [
        {
          name: "QR Code Generator",
          path: "/en-US/tool/qr-generator",
          icon: Hash,
          description: "Generate QR codes with custom data",
        },
        {
          name: "Barcode Creator",
          path: "/en-US/tool/barcode-creator",
          icon: Binary,
          description: "Create various barcode formats",
        },
        {
          name: "Favicon Generator",
          path: "/en-US/tool/favicon-generator",
          icon: Globe,
          description: "Generate favicons for websites",
        },
        {
          name: "Icon Generator",
          path: "/en-US/tool/icon-generator",
          icon: Smartphone,
          description: "Create app icons for iOS and Android",
        },
        {
          name: "Social Media Resize",
          path: "/en-US/tool/social-resize",
          icon: Users,
          description: "Resize images for social media platforms",
        },
        {
          name: "Print Optimizer",
          path: "/en-US/tool/print-optimizer",
          icon: Printer,
          description: "Optimize images for high-quality printing",
        },
        {
          name: "Web Optimizer",
          path: "/en-US/tool/web-optimizer",
          icon: Wifi,
          description: "Optimize images for web performance",
        },
        {
          name: "Email Optimizer",
          path: "/en-US/tool/email-optimizer",
          icon: Mail,
          description: "Optimize images for email newsletters",
        },
      ],
    },
    {
      title: "Batch Processing",
      icon: Layers,
      color: "emerald",
      description: "Process multiple images simultaneously",
      tools: [
        {
          name: "Batch Resize",
          path: "/en-US/tool/batch-resize",
          icon: Resize,
          description: "Resize multiple images with consistent settings",
        },
        {
          name: "Batch Watermark",
          path: "/en-US/tool/batch-watermark",
          icon: Stamp,
          description: "Add watermarks to multiple images at once",
        },
        {
          name: "Batch Rename",
          path: "/en-US/tool/batch-rename",
          icon: Type,
          description: "Rename multiple image files with patterns",
        },
        {
          name: "Batch Filter",
          path: "/en-US/tool/batch-filter",
          icon: Filter,
          description: "Apply filters to multiple images simultaneously",
        },
        {
          name: "Batch Crop",
          path: "/en-US/tool/batch-crop",
          icon: Crop,
          description: "Crop multiple images to the same dimensions",
        },
        {
          name: "Batch Rotate",
          path: "/en-US/tool/batch-rotate",
          icon: RotateCw,
          description: "Rotate multiple images by the same angle",
        },
        {
          name: "Batch Compress",
          path: "/en-US/tool/batch-compress",
          icon: Archive,
          description: "Compress multiple images for web use",
        },
        {
          name: "Batch Convert",
          path: "/en-US/tool/batch-convert-advanced",
          icon: RefreshCw,
          description: "Advanced batch format conversion with options",
        },
      ],
    },
    {
      title: "Security & Privacy",
      icon: Shield,
      color: "red",
      description: "Protect and secure your images",
      tools: [
        {
          name: "Remove Metadata",
          path: "/en-US/tool/metadata-remove",
          icon: Database,
          description: "Strip EXIF data and location information",
        },
        {
          name: "Face Blur",
          path: "/en-US/tool/face-blur",
          icon: EyeOff,
          description: "Automatically blur faces for privacy protection",
        },
        {
          name: "License Plate Blur",
          path: "/en-US/tool/license-blur",
          icon: Car,
          description: "Detect and blur license plates automatically",
        },
        {
          name: "Text Redaction",
          path: "/en-US/tool/text-redact",
          icon: EyeOff,
          description: "Automatically detect and redact text content",
        },
        {
          name: "Steganography",
          path: "/en-US/tool/steganography",
          icon: Lock,
          description: "Hide secret messages within images",
        },
        {
          name: "Digital Signature",
          path: "/en-US/tool/digital-signature",
          icon: Fingerprint,
          description: "Add digital signatures to verify authenticity",
        },
        {
          name: "Encrypt Images",
          path: "/en-US/tool/image-encrypt",
          icon: Key,
          description: "Password-protect images with encryption",
        },
        {
          name: "Secure Delete",
          path: "/en-US/tool/secure-delete",
          icon: Trash2,
          description: "Permanently delete images beyond recovery",
        },
      ],
    },
  ];

  const getColorClasses = (color: string) => {
    const colors = {
      green: {
        bg: "bg-green-50",
        text: "text-green-600",
        border: "border-green-200",
        gradient: "from-green-500 to-emerald-500",
      },
      purple: {
        bg: "bg-purple-50",
        text: "text-purple-600",
        border: "border-purple-200",
        gradient: "from-purple-500 to-violet-500",
      },
      blue: {
        bg: "bg-blue-50",
        text: "text-blue-600",
        border: "border-blue-200",
        gradient: "from-blue-500 to-cyan-500",
      },
      pink: {
        bg: "bg-pink-50",
        text: "text-pink-600",
        border: "border-pink-200",
        gradient: "from-pink-500 to-rose-500",
      },
      indigo: {
        bg: "bg-indigo-50",
        text: "text-indigo-600",
        border: "border-indigo-200",
        gradient: "from-indigo-500 to-purple-500",
      },
      teal: {
        bg: "bg-teal-50",
        text: "text-teal-600",
        border: "border-teal-200",
        gradient: "from-teal-500 to-cyan-500",
      },
      orange: {
        bg: "bg-orange-50",
        text: "text-orange-600",
        border: "border-orange-200",
        gradient: "from-orange-500 to-red-500",
      },
      red: {
        bg: "bg-red-50",
        text: "text-red-600",
        border: "border-red-200",
        gradient: "from-red-500 to-pink-500",
      },
      gray: {
        bg: "bg-gray-50",
        text: "text-gray-600",
        border: "border-gray-200",
        gradient: "from-gray-500 to-slate-500",
      },
      violet: {
        bg: "bg-violet-50",
        text: "text-violet-600",
        border: "border-violet-200",
        gradient: "from-violet-500 to-purple-500",
      },
      emerald: {
        bg: "bg-emerald-50",
        text: "text-emerald-600",
        border: "border-emerald-200",
        gradient: "from-emerald-500 to-teal-500",
      },
    };
    return colors[color as keyof typeof colors];
  };

  const totalTools = toolCategories.reduce(
    (sum, category) => sum + category.tools.length,
    0
  );

  return (
    <>
      <Helmet>
        <title>
          Image Tools - Professional Image Editor & Converter | Doclair
        </title>
        <meta
          name="description"
          content={`Professional image editing tools with ${totalTools}+ advanced features. AI-powered editing, batch processing, format conversion, and creative effects. Free online image editor.`}
        />
        <meta
          name="keywords"
          content="image editor, photo editor, AI image tools, batch processing, format converter, creative effects, professional photography tools"
        />
        <link rel="canonical" href="https://doclair.com/en-US/image-tools" />
        <meta
          property="og:title"
          content={`${totalTools}+ Professional Image Tools - Edit, Convert & Enhance Images`}
        />
        <meta
          property="og:description"
          content="Complete image editing suite with AI-powered tools, batch processing, creative effects, and professional photography features. Free online image editor."
        />
      </Helmet>

      <div className="min-h-screen bg-gray-50">
        {/* Header */}
        <div className="bg-white border-b border-gray-200">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
            <div className="text-center">
              <div className="inline-flex p-4 bg-gradient-to-br from-green-500 to-emerald-500 rounded-3xl mb-8 shadow-2xl">
                <Image className="h-16 w-16 text-white" />
              </div>
              <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
                <span className="cursive-text text-5xl md:text-6xl text-green-600">
                  Professional
                </span>
                <br />
                Image Tools
              </h1>
              <p className="text-xl text-gray-600 max-w-4xl mx-auto mb-8">
                Complete image editing suite with{" "}
                <span className="cursive-text text-purple-600 text-2xl">
                  {totalTools}+
                </span>{" "}
                professional tools. AI-powered editing, batch processing,
                creative effects, and{" "}
                <span className="cursive-text text-blue-600 text-xl">
                  enterprise-grade
                </span>{" "}
                features.
              </p>

              {/* Feature highlights */}
              <div className="flex flex-wrap justify-center gap-4 mb-8">
                <div className="bg-purple-50 text-purple-700 px-4 py-2 rounded-full text-sm font-semibold flex items-center gap-2">
                  <Sparkles className="h-4 w-4" />
                  AI-Powered Tools
                </div>
                <div className="bg-blue-50 text-blue-700 px-4 py-2 rounded-full text-sm font-semibold flex items-center gap-2">
                  <Layers className="h-4 w-4" />
                  Batch Processing
                </div>
                <div className="bg-green-50 text-green-700 px-4 py-2 rounded-full text-sm font-semibold flex items-center gap-2">
                  <Zap className="h-4 w-4" />
                  Lightning Fast
                </div>
                <div className="bg-orange-50 text-orange-700 px-4 py-2 rounded-full text-sm font-semibold flex items-center gap-2">
                  <Shield className="h-4 w-4" />
                  Privacy First
                </div>
              </div>

              {/* Stats */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-2xl mx-auto">
                <div className="text-center">
                  <div className="text-3xl font-bold text-green-600 mb-1">
                    {totalTools}+
                  </div>
                  <div className="text-sm text-gray-600 font-medium">
                    Professional Tools
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold text-purple-600 mb-1">
                    12
                  </div>
                  <div className="text-sm text-gray-600 font-medium">
                    AI-Powered
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold text-blue-600 mb-1">8</div>
                  <div className="text-sm text-gray-600 font-medium">
                    Batch Tools
                  </div>
                </div>
                <div className="text-center">
                  <div className="text-3xl font-bold text-orange-600 mb-1">
                    20+
                  </div>
                  <div className="text-sm text-gray-600 font-medium">
                    File Formats
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Tools Grid */}
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="space-y-16">
            {toolCategories.map((category, categoryIndex) => {
              const colorClasses = getColorClasses(category.color);
              return (
                <div key={categoryIndex} className="apple-floating-card">
                  <div className="flex items-center mb-8">
                    <div
                      className={`inline-flex p-4 rounded-2xl bg-gradient-to-r ${colorClasses.gradient} mr-6 shadow-lg`}
                    >
                      <category.icon className="h-8 w-8 text-white" />
                    </div>
                    <div>
                      <h2 className="text-3xl font-bold text-gray-900 mb-2">
                        {category.title}
                      </h2>
                      <p className="text-gray-600 text-lg">
                        {category.description}
                      </p>
                      <div className="text-sm text-gray-500 mt-1">
                        {category.tools.length} tools available
                      </div>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                    {category.tools.map((tool, toolIndex) => (
                      <Link
                        key={toolIndex}
                        to={tool.path}
                        className="group bg-gray-50/80 hover:bg-white border border-gray-200/50 hover:border-gray-300 rounded-2xl p-6 transition-all duration-500 hover:shadow-xl hover:-translate-y-2"
                      >
                        <div className="flex items-start mb-4">
                          <div
                            className={`inline-flex p-3 rounded-xl ${colorClasses.bg} mr-4 group-hover:bg-gradient-to-r group-hover:${colorClasses.gradient} transition-all duration-500 shadow-sm group-hover:shadow-lg`}
                          >
                            <tool.icon
                              className={`h-6 w-6 ${colorClasses.text} group-hover:text-white transition-colors duration-500`}
                            />
                          </div>
                          <div className="flex-1 min-w-0">
                            <h3 className="text-lg font-bold text-gray-900 group-hover:text-blue-600 transition-colors duration-500 mb-2">
                              {tool.name}
                            </h3>
                            <p className="text-sm text-gray-600 leading-relaxed">
                              {tool.description}
                            </p>
                          </div>
                        </div>

                        <div className="flex items-center justify-between">
                          <div
                            className={`category-badge ${colorClasses.bg} ${colorClasses.text} border ${colorClasses.border}`}
                          >
                            {category.title}
                          </div>
                          <ArrowRight className="h-4 w-4 text-gray-400 group-hover:text-blue-600 group-hover:translate-x-1 transition-all duration-500" />
                        </div>
                      </Link>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Features Section */}
        <div className="bg-gradient-to-r from-green-600 via-blue-600 to-purple-600 text-white py-20 relative overflow-hidden">
          <div className="absolute inset-0 bg-black/10"></div>

          {/* Floating elements */}
          <div className="absolute top-10 left-10 floating-element opacity-20">
            <Sparkles className="h-8 w-8 text-white" />
          </div>
          <div
            className="absolute bottom-10 right-10 floating-element opacity-20"
            style={{ animationDelay: "4s" }}
          >
            <Palette className="h-10 w-10 text-white" />
          </div>

          <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Why Choose Our{" "}
                <span className="cursive-text text-5xl">Image</span> Tools?
              </h2>
              <p className="text-xl text-green-100 max-w-3xl mx-auto">
                Professional-grade image processing with{" "}
                <span className="cursive-text text-2xl text-white">
                  cutting-edge
                </span>{" "}
                AI technology and intuitive design.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <div className="text-center bg-white/10 backdrop-blur-xl rounded-2xl p-8 hover:bg-white/20 transition-all duration-500">
                <Sparkles className="h-16 w-16 mx-auto mb-6 text-green-200" />
                <h3 className="text-xl font-bold mb-4">
                  AI-Powered Processing
                </h3>
                <p className="text-green-100">
                  Advanced machine learning for intelligent background removal,
                  object detection, and enhancement.
                </p>
              </div>
              <div className="text-center bg-white/10 backdrop-blur-xl rounded-2xl p-8 hover:bg-white/20 transition-all duration-500">
                <Layers className="h-16 w-16 mx-auto mb-6 text-blue-200" />
                <h3 className="text-xl font-bold mb-4">Batch Processing</h3>
                <p className="text-blue-100">
                  Process hundreds of images simultaneously with consistent
                  settings and professional results.
                </p>
              </div>
              <div className="text-center bg-white/10 backdrop-blur-xl rounded-2xl p-8 hover:bg-white/20 transition-all duration-500">
                <Shield className="h-16 w-16 mx-auto mb-6 text-purple-200" />
                <h3 className="text-xl font-bold mb-4">Privacy & Security</h3>
                <p className="text-purple-100">
                  All processing happens locally in your browser. Your images
                  never leave your device.
                </p>
              </div>
              <div className="text-center bg-white/10 backdrop-blur-xl rounded-2xl p-8 hover:bg-white/20 transition-all duration-500">
                <Zap className="h-16 w-16 mx-auto mb-6 text-yellow-200" />
                <h3 className="text-xl font-bold mb-4">
                  Lightning Performance
                </h3>
                <p className="text-yellow-100">
                  WebAssembly-powered algorithms deliver professional results in
                  seconds, not minutes.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="bg-white py-20">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <div className="mb-8">
              <Image className="h-16 w-16 mx-auto text-green-600 mb-6" />
            </div>

            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Ready to{" "}
              <span className="cursive-text text-5xl text-green-600">
                Transform
              </span>{" "}
              Your Images?
            </h2>

            <p className="text-xl text-gray-600 mb-10 max-w-3xl mx-auto">
              Join millions of professionals who trust our{" "}
              <span className="cursive-text text-purple-600 text-2xl">
                advanced
              </span>{" "}
              image tools for their creative and business needs.
            </p>

            <div className="flex flex-col sm:flex-row gap-6 justify-center">
              <Link
                to="/en-US/tool/background-remove"
                className="bg-gradient-to-r from-green-600 to-emerald-600 text-white px-10 py-4 rounded-full font-bold text-lg hover:from-green-700 hover:to-emerald-700 transition-all duration-500 flex items-center justify-center gap-3 shadow-2xl hover:scale-105"
              >
                <Eraser className="h-6 w-6" />
                Try Background Remover
              </Link>
              <Link
                to="/en-US/tool/image-resize"
                className="bg-white border-2 border-gray-300 text-gray-800 px-10 py-4 rounded-full font-bold text-lg hover:border-gray-400 hover:bg-gray-50 transition-all duration-500 flex items-center justify-center gap-3 shadow-lg hover:scale-105"
              >
                <Resize className="h-6 w-6" />
                Start with Resize Tool
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default ImageTools;
